name: Build



on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build: 
    env:
      configuration: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install dotnet
        uses: actions/setup-dotnet@v1
      - name: restore
        run: dotnet restore
      - name: build
        run: dotnet build --no-restore --configuration ${{ env.configuration }}
      - name: test
        run: dotnet test --no-build --verbosity normal --configuration ${{ env.configuration }}
      - name: publish
        run: dotnet publish --configuration ${{ env.configuration }} --output ${{runner.temp}}/artifact
      - name: publish-artifact
        uses: actions/upload-artifact@v4
        with: 
          name: publish
          path: ${{runner.temp}}/artifact
      
      
